package org.iii.ufo.shdep.nodes;

public enum Op {
	illegalTok(null),
	_EOF("_EOF"),      // EOF
	_Lit("_Lit"),      // Lit
	_LitWord("_LitWord"),  // LitWord
	_LitRedir("_LitRedir"), // LitRedir
	sglQuote("'"),
	dblQuote("\""),
	bckQuote("`"),
	and("&"),
	andAnd("&&"),
	orOr("||"),
	or("|"),
	orAnd("|&"),
	dollar("$"),
	dollSglQuote("$'"),
	dollDblQuote("$\""),
	dollBrace("${"),
	dollBrack("$["),
	dollParen("$("),
	dollDblParen("$(("),
	leftBrack("["),
	leftParen("("),
	dblLeftParen("(("),
	rightBrace("}"),
	rightBrack("]"),
	rightParen(")"),
	dblRightParen("))"),
	semicolon(";"),
	dblSemicolon(";;"),
	semiAnd(";&"),
	dblSemiAnd(";;&"),
	semiOr(";|"),
	exclMark("!"),
	addAdd("++"),
	subSub("--"),
	star("*"),
	power("**"),
	equal("=="),
	nequal("!="),
	lequal("<="),
	gequal(">="),
	addAssgn("+="),
	subAssgn("-="),
	mulAssgn("*="),
	quoAssgn("/="),
	remAssgn("%="),
	andAssgn("&="),
	orAssgn("|="),
	xorAssgn("^="),
	shlAssgn("<<="),
	shrAssgn(">>="),
	rdrOut(">"),
	appOut(">>"),
	rdrIn("<"),
	rdrInOut("<>"),
	dplIn("<&"),
	dplOut(">&"),
	clbOut(">|"),
	hdoc("<<"),
	dashHdoc("<<-"),
	wordHdoc("<<<"),
	rdrAll("&>"),
	appAll("&>>"),
	cmdIn("<("),
	cmdOut(">("),
	plus("+"),
	colPlus(":+"),
	minus("-"),
	colMinus(":-"),
	quest("?"),
	colQuest(":?"),
	assgn("="),
	colAssgn(":="),
	perc("%"),
	dblPerc("%%"),
	hash("#"),
	dblHash("##"),
	caret("^"),
	dblCaret("^^"),
	comma(","),
	dblComma(",,"),
	at("@"),
	slash("/"),
	dblSlash("//"),
	colon(":"),
	tsExists("-e"),
	tsRegFile("-f"),
	tsDirect("-d"),
	tsCharSp("-c"),
	tsBlckSp("-b"),
	tsNmPipe("-p"),
	tsSocket("-S"),
	tsSmbLink("-L"),
	tsSticky("-k"),
	tsGIDSet("-g"),
	tsUIDSet("-u"),
	tsGrpOwn("-G"),
	tsUsrOwn("-O"),
	tsModif("-N"),
	tsRead("-r"),
	tsWrite("-w"),
	tsExec("-x"),
	tsNoEmpty("-s"),
	tsFdTerm("-t"),
	tsEmpStr("-z"),
	tsNempStr("-n"),
	tsOptSet("-o"),
	tsVarSet("-v"),
	tsRefVar("-R"),
	tsReMatch("=~"),
	tsNewer("-nt"),
	tsOlder("-ot"),
	tsDevIno("-ef"),
	tsEql("-eq"),
	tsNeq("-ne"),
	tsLeq("-le"),
	tsGeq("-ge"),
	tsLss("-lt"),
	tsGtr("-gt"),
	globQuest("?("),
	globStar("*("),
	globPlus("+("),
	globAt("@("),
	globExcl("!(");
	
	private static final Op[] values_ = values(); //cache
	public static Op from(int i){
		return values_[i];
	}
	
	private final String lit; 
	private Op(String lit){
		this.lit = lit;
	}
	
	public String lit(){ return lit;}
}
