/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tsungtatsai' at '2017/5/2 上午 10:19' with Gradle 2.14
 *
 * @author tsungtatsai, @date 2017/5/2 上午 10:19
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
